- hosts: all
  become: true

  pre_tasks:
    - name: Install openJDK and other packages
      yum:
        name:
          - java-1.8.0-openjdk
          - maven
          - git
          - firewalld
        state: present
        update_cache: yes

  roles:
    - spring-petclinic